### ISSUE TITLE
small bugs?

### ISSUE THREAD

**Issue by Case2k** [Gpopcorn/3D-Graphics-Engine#1]
Hii, i really love your engine!
But i had 2 small problems getting it up running.

in line 570 of main.py i changed

pygame.draw.circle(display, RED, (point[0], point[1]), 4)
to
pygame.draw.circle(display, RED, (int(point[0]),int(point[1])), 4)

and in line 1 of matrix.py i changed 

def multiplyMatrix(a, b):
to
def multiply_matrix(a, b):

then all runs fine :)

Many greetings Case

PS: i will maybe do some small changes to it, maybe a button for a fixed lightsource would be nice.  :)

**Comment by Gpopcorn** [comment]
Sorry for the wait on resolving this issue (on vacation), but now it should work better for when more people want to use it! Thanks for bringing this to my concern!
